name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
      
    - name: Prepare Environment
      run: |
          sudo apt update
          sudo docker-php-ext-install zip
      
    - name: Copy .env
      run: cp .env.testing .env
      
    - name: Install Dependencies
      run: composer update
      
    - name: Generate key
      run: php artisan key:generate
      
    - name: Create Database
      run: |
        touch database/database.sqlite
        php artisan migrate --env=testing
        
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
